### ISSUE TITLE
IDEs can not detect the classes/functions

### ISSUE THREAD

**Issue by Hamza5** [wensheng/hedera-sdk-py#1]
First, thanks for this nice library.
Second, it seems that the IDEs (PyCharm Professional for example) can not recognize any classes or functions inside this library. I know that this happens because everything is auto-generated from wrapping the Java SDK, but I want to ask whether it is possible to include at least the signature of the classes and the functions in the source files, so the IDEs stop complaining about them and help us with good code completion.

![Image 1](https://user-images.githubusercontent.com/7011111/120933393-e36e3280-c6f1-11eb-8ec2-146f3f3c6ef1.jpg)

**Comment by biatti** [comment]
Having the same issue with PyCharm Pro!

**Comment by zmeeust** [comment]
Use this:
`from hedera.generated import AccountId, AccountCreateTransaction, Client`

**Comment by wensheng** [comment]
Sorry I don't use IDE for Python programming.  I will do some research on this.

**Comment by mowliv** [comment]
> Use this: `from hedera.generated import AccountId, AccountCreateTransaction, Client`

Would be good to change the examples to use this.
