### ISSUE TITLE
No such method error for com.google.protobuf.GeneratedMessageLite.registerDefaultInstance

### ISSUE THREAD

**Issue by paliwalg** [wensheng/hedera-sdk-py#2]
I am trying to generate the python wrapper for Hedera Java DID SDK [https://github.com/hashgraph/did-sdk-java](url) 
using the same approach as with this project.

I can see python wrappers are generated successfully, but when I am trying to use them, it fails with the error as :

  File "jnius/jnius_export_class.pxi", line 270, in jnius.JavaClass.__init__
  File "jnius/jnius_export_class.pxi", line 370, in jnius.JavaClass.call_constructor
  File "jnius/jnius_jvm_dlopen.pxi", line 91, in jnius.create_jnienv
jnius.JavaException: JVM exception occurred: 'void com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(java.lang.Class, com.google.protobuf.GeneratedMessageLite)' java.lang.NoSuchMethodError

Any idea what I might have done it wrongly or I have missed here ?

Let me know if you need more information.

**Comment by laoym88** [comment]
Am having same protobuf issues after ContractCallQuery()

..., print(query_result.rawResult)
it outputs <com.google.protobuf.ByteString at 0x7fa4f5aba200 jclass=com/google/protobuf/ByteString jself=<LocalRef obj=0x38957d0 at 0x7fa520f92a50>>

Managed to view ContractFunctionResult{ .... rawResult='00000...00' ...} separately.

Couldnt decode this ByteString.

Please help.  Thanks in advance
