### ISSUE TITLE
Can't write file 

### ISSUE THREAD

**Issue by automateyournetwork** [wensheng/hedera-sdk-py#5]
Hello - from CentOS 7 I am unable to write files to testnet - could you help me troubleshoot this?

export JAVA_HOME=/usr/lib/jvm/java-11-openjdk/
OPERATOR_ID={ Hedera account id }
OPERATOR_PRIVATE_KEY={ Hedera private key }

client = Client.forTestnet()
client.setOperator(OPERATOR_ID, OPERATOR_PRIVATE_KEY)
tran = FileCreateTransaction()
fileContents = raw_json
resp = tran.setKeys(OPERATOR_PRIVATE_KEY.getPublicKey()).setContents(fileContents).setMaxTransactionFee(Hbar(2)).execute(client)

resp = tran.setKeys(OPERATOR_PRIVATE_KEY.getPublicKey()).setContents(fileContents).setMaxTransactionFee(Hbar(2)).execute(client)
  File "jnius/jnius_export_class.pxi", line 1177, in jnius.JavaMultipleMethod.__call__
  File "jnius/jnius_export_class.pxi", line 885, in jnius.JavaMethod.__call__
  File "jnius/jnius_export_class.pxi", line 965, in jnius.JavaMethod.call_method
  File "jnius/jnius_utils.pxi", line 91, in jnius.check_exception
jnius.JavaException: JVM exception occurred: exceeded maximum attempts for request with last exception being com.hedera.hashgraph.sdk.MaxAttemptsExceededException

Thank you

**Comment by laoym88** [comment]
Hi,

Try this code:

cur_dir = os.path.abspath(os.path.dirname(__file__))
jsonf = open(os.path.join(cur_dir, "raw_json"))
fileContents = json.load(jsonf)

tran = (FileCreateTransaction()
         .setKeys(OPERATOR_KEY)
         .setContents( fileContents['object'].encode() )
         .setMaxTransactionFee(Hbar(2))
         .execute(client))
receipt = tran.getReceipt(client)

**Comment by automateyournetwork** [comment]
I was able to get this working by updating the JDK to 18 on CentOS !
